name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * * || 0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: FahdAzouz
      - name: Configure Git Credentials
        run: |
          git config --global user.name FahdAzouz
          git config --global user.email fahdstudies00@gmail.com
          git config --global credential.helper store
          git config --global user.password ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          git add -A .
          git commit -m "generated"
          git push
